spring.application.name=2026
# =====================
# SERVER
# =====================
server.port=2500
server.address=0.0.0.0

# =====================
# H2 (FILE MODE - persistente)
# =====================
spring.datasource.url=jdbc:h2:file:./data/websearch
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# =====================
# H2 CONSOLE
# =====================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console